project:
  type: website

website:
  title: "<img src='/images/fatalshootings.jpeg' alt='Stock Symbol' style='width: 2.6em; height: 2.2em; border-radius: 30%;'> <b>Analysis of Fatal Police Shootings</b>"
  navbar:
    right:
      - icon: github
        href: https://github.com/INFO-526-S24/project-final-RoboCops
    left:
      - text: Project
        href: index.qmd
      - text: Proposal
        href: proposal.qmd
      - text: Presentation
        href: presentation.qmd
      - text: Dashboard
        href: Dashboard.qmd
      - text: About
        href: about.qmd

format:
  html:
    theme:
      light: flatly
      dark: darkly
    toc: true

  revealjs:
    theme:  [simple,data/customtheming.scss]
  
  dashboard:
    theme:  united

execute:
  freeze: auto
